# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - XpenseTracker1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install npm packages Backend
        run: |
          cd Backend
          npm install

      - name: Install npm packages Frontend
        run: |
          cd Frontend
          npm install

      - name: Build Frontend
        run: |
          cd Frontend
          CI=false npm run build

      - name: Copy Frontend build to Backend
        run: cp -r Frontend/build Backend/public

      - name: Zip artifact for deployment
        run: zip -r release.zip Backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B3AE6837BA647EABFA33327B048DD37 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8731FBFB170E4CD3BDF18FEACAFF8174 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C47639FA9DBA48DF87729F89FF939309 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "XpenseTracker1"
          slot-name: "Production"
          package: .
